apiVersion: v1
kind: PersistentVolume
metadata:
  name: dumpy-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: nas-server
    path: /shared-location
  claimRef:
    namespace: dumpy
