apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dumpy-pvc
  namespace: dumpy
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: dumpy-pv
  volumeMode: Filesystem
