apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: dumpy
  name: pod-creator-binding
subjects:
  - kind: Group
    name: system:authenticated
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-creator
  apiGroup: rbac.authorization.k8s.io