apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: ""
  name: shared-resource-consumer
  namespace: openshift
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: shared-resource-consumer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated